### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by sami3898** [sumitkolhe/inshorts-api-v2#14]
<img width="776" alt="image" src="https://github.com/sumitkolhe/inshorts-api/assets/32996863/faeada60-8ad8-4454-9807-d770532179ef">

API has been down getting the above message in all API endpoints except the "Topics" endpoint

**Comment by sumitkolhe** [comment]
Seems to be working fine https://inshorts.me/news/trending?offset=0&limit=10
