### ISSUE TITLE
API url not working 

### ISSUE THREAD

**Issue by AvaiyaKashyap** [sumitkolhe/inshorts-api-v2#17]
this link is not working is it offline or what?

https://inshorts-news-knbl9pokb-sumanjay.vercel.app/news?category=all

![image](https://github.com/sumitkolhe/inshorts-api/assets/88942744/bf2781e0-ca24-4b9f-b263-21c227d7631c)

**Comment by sumitkolhe** [comment]
the url is https://inshorts.me
