### ISSUE TITLE
Pagination Issues.

### ISSUE THREAD

**Issue by soumyajitsaha72** [sumitkolhe/inshorts-api-v2#5]
Buddy... I'm working with this API currently. I'm facing one issue currently...which is pagination. I want to create infinite scroll effect... but the API doesn't have any offset field(as per documentation). Can you fix this part... add a offset query param like limit.

**Comment by sumitkolhe** [comment]
@soumyajitsaha72 `offset` and `limit` have been added in the new implementation in #8 do check out new docs at - https://docs.inshorts.me
