### ISSUE TITLE
Same news repeating again and again

### ISSUE THREAD

**Issue by samarthasthan** [sumitkolhe/inshorts-api-v2#7]
@sumitkolhe Hey, can you help me with how can I get different news every time I call API

**Comment by sumitkolhe** [comment]
News updates periodically, so if there's no new news since you last made a request, you will get same news again

**Comment by samarthasthan** [comment]
what languages are you using in it? NodeJS? or what

**Comment by sumitkolhe** [comment]
Its written in typescript
